title: Maija Li Raudaskoski
logo: /assets/img/me.jpg
description: This page was created as the final project assignment for the command line course.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
